会場をぴーぴに変更した
Hyogo23014/ichiyasaGitSample pull request #1
Opened 2024-06-06 05:29 UTC by Hyogo23014

###変更内容
会場をぴーぴに変更

###背景
ぴーぴさんが会場を貸してくれることになった

2024-06-06 05:32 UTC, matsui0412 reviewed
見ました

2024-06-06 05:32 UTC, matsui0412 commented on index.html
> +                        <p>株式会社ぴーぴ イベントセミナー会場</p>
いいね

2024-06-06 05:43 UTC, matsui0412 commented
嗨，來自遠方的你，今天會收到一個驚喜。

2024-06-12 02:35 UTC, matsui0412 requested changes
修正ありがとうございます！！

2024-06-12 02:35 UTC, matsui0412 commented on index.html
> +                        <p>株式会社ぴーぴ イベントセミナー会場</p>
株式会社松井に変えてください

2024-06-12 03:08 UTC, matsui0412 requested changes
ナス！

2024-06-12 03:08 UTC, matsui0412 commented on index.html
> +                        <p>インプレス イベントセミナー会場</p>
会場変更ありがとナス！

2024-06-12 03:28 UTC, matsui0412 approved these changes

2024-06-12 03:30 UTC, matsui0412 approved these changes

2024-06-13 04:44 UTC, atsuki-g-2 approved these changes
ｊｊｊ

2024-06-13 04:57 UTC, merged