会場をインプレスに変更した
Hyogo23014/ichiyasaGitSample pull request #2
Opened 2024-06-12 02:56 UTC by Hyogo23014

##　変更内容
イベント開催会場を「株式会社インプレス」に更新しました。

###　背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2024-06-12 03:00 UTC, atsuki-g-2 requested changes
ヒャッハー！

2024-06-12 03:00 UTC, atsuki-g-2 commented on index.html
> +                        <p>インプレス イベントセミナー会場</p>
しっかりしろ

2024-06-12 03:30 UTC, atsuki-g-2 approved these changes

2024-06-13 04:32 UTC, atsuki-g-2 approved these changes
承諾する

2024-06-13 04:42 UTC, matsui0412 approved these changes
おｋ

2024-06-13 04:42 UTC, matsui0412 commented on index.html
> +                        <p>インプレス イベントセミナー会場</p>
やりますねえ！！！
![que-14299263464](https://github.com/Hyogo23014/ichiyasaGitSample/assets/171759659/4d4d66c8-6a98-4086-b593-6e8a92f4bc62)

2024-06-13 04:57 UTC, merged